---
title: "data from web"
author: "hanfu shi"
date: "2021/10/19"
output: github_document
editor_options: 
  chunk_output_type: console
---

#Setting
```{r}
library(tidyverse)

library(rvest)
library(httr)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")

str_detect(string_vec, "e")

str_replace(string_vec, "jeff", "Jeff")
```



```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")#begin with i think

str_detect(string_vec, "i think$")# end with i think
``
```


```{r}

string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush")#capital B or lowercase B

```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")#both 0-9 and a-z are included


```



```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")# dot . match everything
str_detect(string_vec, "7\\.11")#find exactaly a dot character
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")

```




```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex

as.numeric(vec_sex)

vec_sex = fct_relevel(vec_sex, "male")
vec_sex

as.numeric(vec_sex)
```

```{r}


```




```{r}


```



```{r}


```